/* refs.c - lock-step harness around sbc09's v09s.c (instruction-set reference)
 *
 * v09s.c (GPLv2, lives in the sbc09 checkout, not in this repository) is included via a
 * generated copy in which a few defects are corrected (see patch_v09s.py).  Its instruction table is stepped one instruction at
 * a time and the architectural state *before* each instruction plus the number
 * of bus cycles consumed by the previous one are written out.
 *
 *   refs -img f.bin -load 0x1000 -pc 0x1000 -n N -trace ref.trace -cycles ref.cyc
 */
#define main v09s_main
#include "v09s_fixed.c"   /* generated by patch_v09s.py from sbc09/src/v09s.c */
#undef main

int main(int argc, char **argv) {
  const char *img = 0, *trace = "refs.trace", *cyc = "refs.cyc";
  long load = 0, start = 0, n = 100000;
  const char *dump = 0;
  int i;
  for (i = 1; i < argc; i++) {
    if (!strcmp(argv[i], "-img")) img = argv[++i];
    else if (!strcmp(argv[i], "-load")) load = strtol(argv[++i], 0, 0);
    else if (!strcmp(argv[i], "-pc")) start = strtol(argv[++i], 0, 0);
    else if (!strcmp(argv[i], "-n")) n = strtol(argv[++i], 0, 0);
    else if (!strcmp(argv[i], "-trace")) trace = argv[++i];
    else if (!strcmp(argv[i], "-cycles")) cyc = argv[++i];
    else if (!strcmp(argv[i], "-dump")) dump = argv[++i];
    else { fprintf(stderr, "refs: bad arg %s\n", argv[i]); return 2; }
  }
  FILE *f = fopen(img, "rb");
  if (!f) { perror(img); return 2; }
  size_t len = fread(mem + load, 1, 65536 - load, f);
  (void)len;
  fclose(f);
  FILE *tf = fopen(trace, "w"), *cf = fopen(cyc, "w");
  pcreg = start; sreg = 0; dpreg = 0; ccreg = 0x50; iflag = 0;
  for (long k = 0; k < n; k++) {
    fprintf(tf, "%04x %02x %02x %04x %04x %04x %04x %02x %02x\n", pcreg, *areg, *breg, xreg, yreg, ureg,
            sreg, dpreg, ccreg);
    ireg = mem[pcreg++];
    cycles = 0;
    (*instrtable[ireg])();
    fprintf(cf, "%d\n", cycles);
  }
  fclose(tf); fclose(cf);
  if (dump) { FILE *d = fopen(dump, "wb"); fwrite(mem, 1, 65536, d); fclose(d); }
  return 0;
}
